/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantIndexRouteImport } from './routes/plant.index'
import { Route as PlantWavesRouteImport } from './routes/plant.waves'
import { Route as PlantHdbRouteImport } from './routes/plant.hdb'
import { Route as PlantSuttaJobIdRouteImport } from './routes/plant.sutta.$jobId'

const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIndexRoute = PlantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlantRoute,
} as any)
const PlantWavesRoute = PlantWavesRouteImport.update({
  id: '/waves',
  path: '/waves',
  getParentRoute: () => PlantRoute,
} as any)
const PlantHdbRoute = PlantHdbRouteImport.update({
  id: '/hdb',
  path: '/hdb',
  getParentRoute: () => PlantRoute,
} as any)
const PlantSuttaJobIdRoute = PlantSuttaJobIdRouteImport.update({
  id: '/sutta/$jobId',
  path: '/sutta/$jobId',
  getParentRoute: () => PlantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plant': typeof PlantRouteWithChildren
  '/plant/hdb': typeof PlantHdbRoute
  '/plant/waves': typeof PlantWavesRoute
  '/plant/': typeof PlantIndexRoute
  '/plant/sutta/$jobId': typeof PlantSuttaJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plant/hdb': typeof PlantHdbRoute
  '/plant/waves': typeof PlantWavesRoute
  '/plant': typeof PlantIndexRoute
  '/plant/sutta/$jobId': typeof PlantSuttaJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plant': typeof PlantRouteWithChildren
  '/plant/hdb': typeof PlantHdbRoute
  '/plant/waves': typeof PlantWavesRoute
  '/plant/': typeof PlantIndexRoute
  '/plant/sutta/$jobId': typeof PlantSuttaJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plant'
    | '/plant/hdb'
    | '/plant/waves'
    | '/plant/'
    | '/plant/sutta/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plant/hdb' | '/plant/waves' | '/plant' | '/plant/sutta/$jobId'
  id:
    | '__root__'
    | '/'
    | '/plant'
    | '/plant/hdb'
    | '/plant/waves'
    | '/plant/'
    | '/plant/sutta/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlantRoute: typeof PlantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/': {
      id: '/plant/'
      path: '/'
      fullPath: '/plant/'
      preLoaderRoute: typeof PlantIndexRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/waves': {
      id: '/plant/waves'
      path: '/waves'
      fullPath: '/plant/waves'
      preLoaderRoute: typeof PlantWavesRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/hdb': {
      id: '/plant/hdb'
      path: '/hdb'
      fullPath: '/plant/hdb'
      preLoaderRoute: typeof PlantHdbRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/sutta/$jobId': {
      id: '/plant/sutta/$jobId'
      path: '/sutta/$jobId'
      fullPath: '/plant/sutta/$jobId'
      preLoaderRoute: typeof PlantSuttaJobIdRouteImport
      parentRoute: typeof PlantRoute
    }
  }
}

interface PlantRouteChildren {
  PlantHdbRoute: typeof PlantHdbRoute
  PlantWavesRoute: typeof PlantWavesRoute
  PlantIndexRoute: typeof PlantIndexRoute
  PlantSuttaJobIdRoute: typeof PlantSuttaJobIdRoute
}

const PlantRouteChildren: PlantRouteChildren = {
  PlantHdbRoute: PlantHdbRoute,
  PlantWavesRoute: PlantWavesRoute,
  PlantIndexRoute: PlantIndexRoute,
  PlantSuttaJobIdRoute: PlantSuttaJobIdRoute,
}

const PlantRouteWithChildren = PlantRoute._addFileChildren(PlantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlantRoute: PlantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
